version: '3.8'

services:
  # Serviço 1: Aplicação PHP
  app:
    image: mbrito19/meu-dashboard-php-mysql:v1
    ports:
      - "80:80"
    networks:
      - app-network
    deploy:
      # A tarefa da Aula 10 pedia 5 réplicas
      replicas: 5
      restart_policy:
        condition: on-failure

  # Serviço 2: Banco de Dados MariaDB
  db:
    image: mariadb:10.6 
    networks:
      - app-network
    environment:
      MARIADB_DATABASE: britinho
      MARIADB_USER: user_britinho
      MARIADB_PASSWORD: StrongPassword123
      MARIADB_ROOT_PASSWORD: RootStrongPassword123
    configs:
      - source: db-init-sql
        target: /docker-entrypoint-initdb.d/init.sql
    volumes:
      - mysql_data:/var/lib/mysql
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure

  # Serviço 3: phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    networks:
      - app-network
    deploy:
      restart_policy:
        condition: on-failure

networks:
  app-network:
    driver: overlay

volumes:
  mysql_data:

configs:
  db-init-sql:
    external: true