version: '3.8'

services:
  app:
    image: mbrito19/meu-dashboard-php-mysql:v1
    ports:
      - "80:80"
    networks:
      - app-network
    deploy:
      replicas: 5 # Aula 10: 5 réplicas
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      placement:
        constraints:
          - node.role == worker # Aula 10: SÓ NOS WORKERS

  db:
    image: mariadb:10.6
    networks:
      - app-network
    environment:
      MARIADB_DATABASE: britinho
      MARIADB_USER: user_britinho
      MARIADB_PASSWORD: StrongPassword123
      MARIADB_ROOT_PASSWORD: RootStrongPassword123
    configs:
      - source: db-init-sql
        target: /docker-entrypoint-initdb.d/init.sql
    volumes:
      - mysql_data:/var/lib/mysql
    deploy:
      replicas: 1 # Aula 10: Sem réplicas (significa 1)
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      placement:
        constraints:
          - node.role == worker # Aula 10: SÓ NOS WORKERS

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    networks:
      - app-network
    deploy:
      replicas: 2 # Aula 10: 2 réplicas
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      placement:
        constraints:
          - node.role == worker # Aula 10: SÓ NOS WORKERS

networks:
  app-network:
    driver: overlay

volumes:
  mysql_data:

configs:
  db-init-sql:
    external: true